### ISSUE TITLE
Rad Viewer R1

### ISSUE THREAD

**Issue by theo-armour** [ladybug-tools/spider#108]
@ladybug-tools/spiders 

@mostaphaRoudsari provided this RAD file: https://github.com/ladybug-tools/spider/blob/master/solar-well/radiance-data-files/sample-file.rad

Here is what the data looks like in 3D:

![image](https://user-images.githubusercontent.com/547626/39232292-aff39730-4821-11e8-8ba3-0cd8fbb26a13.png)

## [Source code]( https://github.com/ladybug-tools/spider/tree/master/solar-well/radiance-data-files )

The code is simplistic and hard-wired to a single file. Future release will add more sophistication and flexibility

**Comment by mostaphaRoudsari** [comment]
Oh wow! that was quick.

The source code in the link is not updated. It looks more like a place holder.

Is it possible to add the option to upload a file via the interface? That way I can test it for more files.

**Comment by theo-armour** [comment]
@mostaphaRoudsari 

> Is it possible to add the option to upload a file via the interface? That way I can test it for more files.

In R2. Also some links fixed

## full screen: [Rad Viewer 2]( https://rawgit.com/ladybug-tools/spider/master/solar-well/rad-viewer/rad-viewer-2.html )

* Add local file open, read and display
* Add toggle rotation
* Add toggle wireframe view

**Comment by mostaphaRoudsari** [comment]
@theo-armour, the link doesn't work but the screenshot is pretty exciting!

**Comment by sariths** [comment]
@theo-armour, this will be super useful!

**Comment by mostaphaRoudsari** [comment]
@theo-armour, Thanks. This is a great sample file for me! I can probably work on the parser to make it more generic.

Is my understanding right that you can only create faces with 3 vertices in THREE.js? In other words if we have a polygon we always need to triangulate it or is there a more generic way?

**Comment by theo-armour** [comment]
@mostaphaRoudsari 

> Is my understanding right that you can only create faces with 3 vertices in THREE.js?

In general, in computer graphics, a 'face' is a triangle. It olden times a 'quad' and a 'face' were mixed together in various ways, but much less so in most updates of most modern apps - but 'your mileage may vary'. 

Given a bunch of triangular faces, however, we may model almost anything. Including, of course, flat multi-sided polygon as specified in RAD files. RAD files - and their polygons - are new to me. I will start by using the code I use to turn gbXML polygons into Three.js Shape meshes. We will see what happens, but I think that all of the data types in Michal's file should be renderable using Three.js without too many issues in the near future.

Putting it another way: rendering any and all geometry in normal RAD files in your browser looks like being quite doable.

Adding colors to the vertices looks doable as well but I have not really started. Please upload some sample files.

**Comment by theo-armour** [comment]
@mostaphaRoudsari @mdengusiak @bwelle 

## full screen: [Rad Viewer 3]( https://rawgit.com/ladybug-tools/spider/master/solar-well/rad-viewer/rad-viewer-3.html )

![image](https://user-images.githubusercontent.com/547626/39351977-1e4dce16-49b8-11e8-83d9-d4d071131cf8.png)

* Add better handling of text attributes in RAD data files
* Better handling of face data

Full polygons with greater than four sides still to be done

**Comment by theo-armour** [comment]
@mostaphaRoudsari @mdengusiak 

Are there any sample results files from a Radiance analysis that we can use to start shading or coloring the polygons?

**Comment by bwelle** [comment]
We will have that shortly from Radiance measure. But we will view it on gbXML geometry since that is where the mesh will have originated. Take radiance results for exterior surfaces from mesh points and trying to tie it to the .rad polygons (at least that I see visually when go to wireframe) will not work as you will have a series of mesh points that fall within the polygon and you would have to do some averaging that could get complex to give a given polygon a mesh.

-----------------------------------------------------------------------------------------------
Benjamin Welle, PhD, PE, LEED AP BD+C
Director of Energy Lab
Nicollett Mall, IDS Center, 80 S 8th St #300, Minneapolis, MN 55402
t 415.856.3000 m 858.344.6858 benjamin.welle@perkinswill.com<mailto:benjamin.welle@perkinswill.com>

Perkins+Will  Ideas + buildings that honor the broader goals of society
perkinswill.com<http://www.perkinswill.com/>|Blog<http://blog.perkinswill.com/> | Facebook<http://www.facebook.com/ideasandbuildings> | Twitter<http://www.perkinswill.com/pages/twitter.html>

**Comment by mdengusiak** [comment]
@theo-armour 
Here is file Radiance from our Webinar
![image](https://user-images.githubusercontent.com/14005893/39798726-9fb23e74-5359-11e8-8f40-47325344eb61.png)
[gridBasedSimulation.zip](https://github.com/ladybug-tools/spider/files/1986609/gridBasedSimulation.zip)

**Comment by mdengusiak** [comment]
Also here London Office

![2018-05-09 08_05_59](https://user-images.githubusercontent.com/14005893/39800515-f558423c-535f-11e8-8ebf-8d31f3b1d003.png)

![2018-05-09 07_57_38](https://user-images.githubusercontent.com/14005893/39800503-e9370ce0-535f-11e8-8831-5ed3a4a85914.png)

[gridBasedSimulationLondonOffice.zip](https://github.com/ladybug-tools/spider/files/1986726/gridBasedSimulationLondonOffice.zip)

**Comment by theo-armour** [comment]
@mdengusiak 

Thanks for these files. The data looks like it's easy to parse.

The only thing holding me back is that we have so many things to play with right now.

**Comment by afomi** [comment]
@theo-armour 

> The only thing holding me back is that we have so many things to play with right now.

What are you referring to? UI features? Open issues? Something else?

I've been thinking about UI paradigms to manage the powerful features I've seen.

**Comment by theo-armour** [comment]
@mdengusiak 

I was referring to all the things we can be doing with Aragog. I see displaying Radiance data as being a whole other kind of effort

**Comment by bwelle** [comment]
Let us please put Radiance Viewer dev on hold. It is a tangent and a derivative of the primary solar/daylighting visualization work and it is simply complicating and delaying our SPEED project development, and will most certainly complicate the Radiance Data visualization work that will not use a .rad file at all. At some point, data visualization methods for Radiance viewer may be migrated to .rad viewer. Thank you.

-----------------------------------------------------------------------------------------------
Benjamin Welle, PhD, PE, LEED AP BD+C
Director of Energy Lab
Nicollett Mall, IDS Center, 80 S 8th St #300, Minneapolis, MN 55402
t 415.856.3000 m 858.344.6858 benjamin.welle@perkinswill.com<mailto:benjamin.welle@perkinswill.com>

Perkins+Will  Ideas + buildings that honor the broader goals of society
perkinswill.com<http://www.perkinswill.com/>|Blog<http://blog.perkinswill.com/> | Facebook<http://www.facebook.com/ideasandbuildings> | Twitter<http://www.perkinswill.com/pages/twitter.html>

**Comment by afomi** [comment]
I'm just onboarding to this project.

Is there a canonical backlog of potential work/features? Is it the `Issues` for this project?

The tools look quite useful, but I'm sensing it may be valuable to tidy things up that would make the code and apps more approachable to new contributors and users.

Thoughts?

**Comment by bwelle** [comment]
Historical background:

At Perkins+Will we are developing a turnkey design and analysis platform for energy and daylighting leveraging as many open source code as possible. Theo got involved to assist with the three.js visualizations. At one point we decided to generate gbXML files from raw three.js geometry in order to convert to OSM files via the OS API. It is from the work to develop the gbXML exporter that the gbXML Viewer work came to be as a side project.

We have recently started the daylighting component of our work. We are implementing (1) solar studies such as shadow range, sunlight hours, and solar radiation (using open source Ladybug data) and (2) point in time and climate-based daylighting metrics via the Radiance measure in OS, which has officially lost funding as Rob Guglielmetti is now leaving NREL. We are also working with Zack Rogers, Rob, and John Mardaljevic. Theo is assisting with visualization of the Radiance output data in three.js with gbXML geometry. The .rad viewer is not necessary for our work and was another offshoot Theo started, which will eventually be a valuable tool to visualize Radiance data. However, we first need to visualize Radiance data with gbXML files. Hence I’m encouraging postponing further functionality for the .rad viewer and focusing on daylighting data integration with the gbXML viewer so our project can meet its release goals and obtain appropriate funding to continue. The same methodology to view Radiance data with a gbXML file in a three.js environment may be applied to using a .rad file. But one step at a time. If we don’t get step 1 (gbXML data viz) working, we may lose funding, not complete it, and step 2 (.rad data viz) will not be able to leverage it’s code.

-----------------------------------------------------------------------------------------------
Benjamin Welle, PhD, PE, LEED AP BD+C
Director of Energy Lab
Nicollett Mall, IDS Center, 80 S 8th St #300, Minneapolis, MN 55402
t 415.856.3000 m 858.344.6858 benjamin.welle@perkinswill.com<mailto:benjamin.welle@perkinswill.com>

Perkins+Will  Ideas + buildings that honor the broader goals of society
perkinswill.com<http://www.perkinswill.com/>|Blog<http://blog.perkinswill.com/> | Facebook<http://www.facebook.com/ideasandbuildings> | Twitter<http://www.perkinswill.com/pages/twitter.html>

**Comment by afomi** [comment]
@bwelle - this context is VERY helpful. Thank You.

I understand the need for product focus and the importance delivering valuable work in relative order - especially as it relates to funding/runway.

My background is in Software Engineering and Product Management, so I naturally have an eye toward the Roadmap, as well as discrete next steps.

Happy to assist where I can.
