### ISSUE TITLE
Build Well Box Shape updates

### ISSUE THREAD

**Issue by theo-armour** [ladybug-tools/spider#23]
@bwelle 

If you increase the total building area, how would you like the length and width of the building to update?

Am I correct in thinking the length stays the same and the width changes?

**Comment by bwelle** [comment]
Here's what I'm thinking...

For all auto-updates to geometry (changing # of floors, building area), we change all sides of the geometry (in this case a box) proportionally to get the right square footage. This will be necessary for the L and U shapes as we can simply reduce one dimension (like you do no for width) due to all the different sides.

So, if building is 4000ft2, 1 floor, 80ft x 50ft, then when I change the number of floors to 2, we know the area of the first floor needs to be reduced by 50% to 2000ft2. So rather than keeping length 80, and reducing width to 25, we would take the fraction reduction in area (0.5) and take the square root of it...(sqrt(0.5)=0.707107. Now that that fraction times both the length and width, and you get length=56.56 and width=35.35. Those are the new dimensions. Multiple the two together, you get 2000. 

Same approach for changing total building area. doubling the area of a single story building means a factor of 2. The sqrt(2)=1.414. Multiply 80*1.414=113.13 and 50*1.414=70.7, the product of those is 8000, or double the original building area of 4000. Maybe we display digits only to the tenth, ,or one decimal place for simplicity. 

The nice thing about this approach is we can apply it to any shape. Take the % change in floor area due to changing total building area or number of floors, take square root, and apply that factor to all existing dimensions.

**Comment by theo-armour** [comment]
got it. And thank you for documenting the thought process clearly

**Comment by bwelle** [comment]
I'm all about documentation. Music to your ears I'm sure.:) We are a rare breed.

**Comment by bwelle** [comment]
From previous email...

a.	Current Bugs:
   i.	Going from Adjacent Building to Box tabs without losing data.
   ii.	Floor Area not updating correctly with new “proportional dimensions” update.

b.	To-Do List:
   i.	Put x,y,z axis on the ground plan, make it black and thicker and larger so it's very clear to the user visually, and put letters x,y,z on them. 3D text.
   ii.	Add new window inputs and logic to place window arrays. Link to Git code posted. Need to add two more inputs to Box tab: # of Windows and a slider for Window Proportions. Theo, I sent you what I have, let me know if you need more.
   iii.	Add N,S,E,W letters to 3D view. Calculate based on angles so updates as rotate building. Make letters 3D.
   iv.	Change “Building Length” to “Length 1 (X1)”. Change “Width 1 (Y1)”. This will help the user understand the dimension better, and associate it with grid dimensions and the equations we show on the 2D view. 
   v.	Create 2D view somewhere that updates with 3D. Orthographic view like you said. Show equations in 2D text along building sides. When first show box, show equations on each side (Length 1 for x side and Width 1= (Building Area)/Length 1 for y side). Theo, we may choose to show equations in terms of x and y, but we can change this ourselves once we see how text laid out.) Once user starts entering new values for independent parameter (Length 1) or changing parameters that change dimensions such as # of Floors, Building Area (maybe orientation too so you don’t have to rotate equations?), we want to start showing actual numerical values for the sides in the 2D view rather than equations. 
   vi.	Add Opacity slider.
   vii.	Have “edges” enabled at all times.
   viii.	How account for the user changing units from IP to SI? Implications for code? Assume the user selects IP or SI at the beginning of the project and it doesn’t change (i.e. they don’t change units mid geometry entry).

**Comment by bwelle** [comment]
e.	General Issues to Address Later:
i.	For a given Building Area, # of floors, perimeter depth, etc. there are only some valid ranges available until the geometry is broken, e.g. a side with length 10 but a perimeter depth of 15. We need to implement logic to prevent these invalid combinations. One option is to eliminate Perimeter Depth as an option and auto-calculate. Another is to show the user somewhere the range of valid values. For Demo, we will simply avoid such situations. But this is high priority for after demo. We may move to geometry based fully on ratios rather than absolute values but need to think this through carefully.
