### ISSUE TITLE
Build Well Space/Zoning Integration

### ISSUE THREAD

**Issue by bwelle** [ladybug-tools/spider#29]
We will need this additional information for gbXML export.

**Comment by theo-armour** [comment]
@chiensiTB @antonszilasi 

**Current Needs**
In order to create well-formed gbXML files based on the shapes in Build Well we will need to supply ID, and other attributes for every item of geometry in the file to be exported. I can create random data for each item, but it would great if we had some actual rules or logic to the information that is applied.

In issue #27, Ben asks for

> Our gbXML will only require the minimum number of objects to define geometry only. All other information is handled outside the gbXML. The objects we will use includes..
> 
> openingTypeEnum
> BuildingStorey
> Azimuth
> Area
> ObjectId
> surfaceTypeEnum
> 
> There are probably some more, we will look to Chien Si to identify them. 

The sooner we start organizing out thoughts regarding collecting and assigning this data the better as I am currently working on the exporter as it is the current critical path item.

An easy way to start might be to add a Markdown file in the main Build Well folder and start adding and editing collaboratively.

**Longer Term**
A couple of days ago, I built a preliminary gbXML Schema Viewer:

[gbxml schema file viewer r1]( http://www.ladybug.tools/spider/read-gbxml/gbxml-schema-file-viewer/)

I hope that the Build Well project can link to the schema and use it a resource and for validation.

**Comment by chiensiTB** [comment]
Most of the information that you will need as per the request above is contained in the Surface object.  Or its child, the Opening Element.  No need to use any other gbXML geometry elements other than the Surface object for this first release....it just makes things more complicated and more overhead to try and do it all.  A majority of the industry relies only on surfaces.

The only thing I see that is not related to either one is BuildingStorey, and to be fair, I have no idea why you would need ObjectId.  This is the only thing in my mind that requires clarification.

The only other thing worth mentioning here is that all Surfaces have an Id attribute, which may be worth exploiting since it would allow you to do a 1-to-1 mapping from OpenStudio to gbXML via the OpenStudio handles, if you were to need them.

It would be great to come up with a features list and a roadmap.

**Comment by theo-armour** [comment]
@chiensiTB 

> It would be great to come up with a features list and a roadmap.

Features list and roadmap here but lagging bhind current reality:

http://www.ladybug.tools/spider/#sandbox/build-well/README.md

> Most of the information that you will need as per the request above is contained in the Surface object. 

Thank you confirming my understanding.

If you go here:

http://www.ladybug.tools/spider/sandbox/build-well/

In left menu: click: 'gbXML Export' then click 'getBuildingData'

A textarea should appear that contains the gbXML for the project. You may also export this data to a file, if you wish by clicking the button just below. You will note that 'Surface' is the only object exported (for the moment.) No openings yet. They - and other details - should start appearing soon.

> The only other thing worth mentioning here is that all Surfaces have an Id attribute

What I need now are the rules for creating/naming the IDs and any the data required by Open Studio for all of the Shapes outlined by Ben elsewhere.  

See you online later today

**Comment by theo-armour** [comment]
@chiensiTB @bwelle 

BTW, the current Building Well roadmap has the gbXML export saving data for all the buildings in the model - and all bundled together in the Surface object. This simple preliminary method can be updated and modified as we progress.

**Comment by bwelle** [comment]
We need to discuss space objects and space type assignment. If we exclude this information now, Anton and I still need to address it to create OSM, i.e. take a given Zone number and assigned space Type from the GUI and associate it with the bounding surfaces....

**Comment by bwelle** [comment]
Theo, everything is in SI now correct?

**Comment by bwelle** [comment]
See [SpaceTypeZoneAssignment.pdf](https://perkinswill.box.com/s/f3208f9m1wsg0vjx1vbmsjr4plywpf1n). 

This is where in the GUI the user can assign Space Types to zones (spaces) to drive load inputs. There are two things relevant to our work here for this page. 

a.	First, we need to provide MicroExcel the 2D view of the footprint shape with the Zone numbers assigned to it. At first, I thought about using a generic fixed diagram, but we may as well have a view from Theo’s code that has the actual footprint geometry the user specified. We don’t care about adjacent buildings in this view, so we want to zoom extents to just the main building. Convention for zone naming is this: Zone 1 is always lower center zone, which usually corresponds to the zone adjacent to Length 1 (or X1 in the attached Footprint Shapes pdf). In the picture attached, Zone 1 is at the top since the shape has been rotated 180 degrees. Once Zone 1 is known, the zones are numbered clockwise until all outer zones have been named. The core is the last zone. For the donut shape, we would have an extra loop of “outer zones”, but forget that for now. So this is one thing we want to show. Anton, I think you can do this.

b.	Second, we need to record what Space Types are assigned to each zone. We need this for the gbXML export. Assume zones are only assigned space types for one floorplan. Then as the # of floors change, the same space types are assigned to the zones directly above it. So in the example above, Zone 1 is also Zone 8 if we go to 2 floors, and receives the same Space Type assignment. That’s how the GUI is set up. So to get the gbXML export on GIT working, I suggest that for the Box you add 5 fields: Zone 1-Zone 5, and have in the dropdown for each the following available Space Types: Office, Conference, Retail. Then for the L-Shape, have 7 fields, etc. That should give us everything we need for the gbXML export.
