### ISSUE TITLE
Update ~ 2017-10-05 ~ Build Well 8.1

### ISSUE THREAD

**Issue by theo-armour** [ladybug-tools/spider#37]
@ladybug-tools/build-well @mdengusiak 

![image](https://user-images.githubusercontent.com/547626/31258397-ca3e19fc-a9f3-11e7-8161-edf4be21e533.png)

## Full Screen latest release: [Build Well]( http://ladybug-tools.github.io/spider/sandbox/build-well/index.html )

Please test: create a building. Save data to file. Open file with gbXML Viewer. Verify OK or issues.

## Change Log

* mnu-gbxml-export.html
	* Beginning to export quite a bit of gbXML data
	[x] 2017-10-01 ~ Export all building geometries
[x] 2017-09-30 ~ Floor area not being updated correctly

**Comment by theo-armour** [comment]
See also #35

**Comment by bwelle** [comment]
@theo-armour 

Bug list..

1. When I delete a building on Adjacent Buildings, then go to Box or L, they reappear.
2. When rotate Box, say 45 degrees, field shows it as -45 degrees.
3. On Menu Template: “Still thinking about best way to deal with updating menu automatically given varying number of facades - from 4 to 12.”
No matter what shape, there are only 4 orientations. They shouldn’t be A-D, they should be N,S,E,W, and a given façade on a building is determined to fall into one of those orientations given the normal angle. Anton didn’t add this to the code apparently.
4. “Also need to consider all the floor by floor zone types” Actually, not in 3D view. Just zone numbers in gbXML export, then on one single 2D view.
5. “Are there any other floor or facade-related design aspects to be taken into consideration?” Nope, just WWR, Fin Depth, and overhang depth by one of 4 major orientations.
6. L-Shape: Default to 10 for perimeter depth otherwise zones aren’t generated correctly. 
7. L-Shape: Length 1 and 2 are both active and independent. Only Length 1 should be. All others driven based on equations provided.

**Comment by theo-armour** [comment]
@bwelle 

Following depends on Build Well R9 -which will be uploaded soon:
 
> When I delete a building on Adjacent Buildings, then go to Box or L, they reappear.

Menu interaction that does not revert scene and buildings to defaults is on the To Do list and will be dealt with after gbXML export is in good shape.
 
> When rotate Box, say 45 degrees, field shows it as -45 degrees.

Fixed I think.

> L-Shape: Default to 10 for perimeter depth otherwise zones aren’t generated correctly

OK now?

> L-Shape: Length 1 and 2 are both active and independent. Only Length 1 should be. All others driven based on equations provided.

Awaiting spreadsheet with working set of calculations for shape parameters.

All other items: still in the works, pending gbXML completion

**Comment by bwelle** [comment]
@theo-armour 

When you upload R9 will check. in meantime, there are some incorrect surfaces being generated for the L-Shape when you click on "edges", see [here](https://perkinswill.box.com/s/zjxwbs31e3s51ihhngd8vfjnxzv9bq6u)

**Comment by theo-armour** [comment]
> there are some incorrect surfaces being generated for the L-Shape when you click on "edges", see here

Fix toggle edges is on the to do list in the read me
