### ISSUE TITLE
Update 2017-10-14 ~ Build Well R10 ~ Many updates

### ISSUE THREAD

**Issue by theo-armour** [ladybug-tools/spider#41]
@ladybug-tools/spiders 

![image](https://user-images.githubusercontent.com/547626/31581163-bb73a8fc-b118-11e7-9e11-e3cbce37c798.png)

_BW R10 showing new 2D report menu - while 3D model session is still active and visible in lower right corner of the window_

## [Read Me]( https://github.com/ladybug-tools/spider/tree/master/build-well )

Much of this upgrade was enabled by the prior effort here: [Single Model Multiple Menus Read Me]( https://github.com/ladybug-tools/spider/tree/master/sandbox/single-model-multiple-menu )

This release fixes a lot of issues and enables a bunch of new features and will enable faster development. Having said that, it's still a puppy and it has not been tested much. Please wait unto 10.1 or 10.2 before hitting on it hard. Of course, if it crashes your system or you can't do something you think it should be doing then please do comment.

Ooops!! gbXML export is not working. Will fix ASAP.

In the mean time, just enjoy the new stuff. And do note that the code has been moved from the Sandbox folder up to the main Spider folder. Build Well is growing up!

## Change Log

* Many updates to Read Me
* Add mnu-template as file and to menu
* Add groundHelper and toggle
* Added credits page - with first set of credits
	* Credits in menu moved to credits page
* Add the start of a 'real time report' page: menu + markdown + html
* Add start of a Settings Spaces menu - with spaces types etc
* Folder moved from sandbox folder to main Spider folder

Older items mostly dealt with
* 2017-10-10 ~ Menu interaction that does not revert scene and objects to defaults. Selecting various, Adjacent objects menu and Shapes menus, etc should maintain current set of object data
* 2017-09-29 ~ Some variables are hardwired to 'The object' string. Should be to whatever you want it to be ( & UUID ).
* 2017-09-28 ~ After going to 'read me' page, next page does not display properly - Click on title to reload the script
* 2017-09-29 ~ Add complete and current set of parameters to 'The object' object - to enable round trip with adj build menu
* 2017-10-02 ~ fix toggle edges
* 2017-10-02 ~ Ground & Helpers don't toggle after change in grid size
* 2017-10-02 ~ Add options to grid size / prevent spurious values
* Add links to credits page
* Enable viewing html & markdown without killing Three.js data

**Comment by mdengusiak** [comment]
@theo-armour 
great progress,  
1. what are those + and - in 3D model?
![image](https://user-images.githubusercontent.com/14005893/31587911-4ef4fe4c-b1ea-11e7-94d2-6c22a1e02a3b.png)

2. I checked why I can not import your gbXML and have this error I used version fromR.10.1:
Your gbXml file does not contain any Shell data for the spaces.
You only have surfaces and spaces

your space only icludes: Name, Description, Area and Volume
![image](https://user-images.githubusercontent.com/14005893/31588041-78add518-b1ec-11e7-817a-83a9b882d9f3.png)

but you missing ShellGeometry
![image](https://user-images.githubusercontent.com/14005893/31588098-42e2933c-b1ed-11e7-8a1b-ea2b4f8b978e.png)

here with details
![image](https://user-images.githubusercontent.com/14005893/31588049-a206ff16-b1ec-11e7-8d15-2f14c8093838.png)

gbXML ShellGeometry
![image](https://user-images.githubusercontent.com/14005893/31588145-062f4556-b1ee-11e7-938b-06dc4c434d87.png)

**Comment by mdengusiak** [comment]
Would be possible that we isolate spaces and see them in 3D?

![image](https://user-images.githubusercontent.com/14005893/31588882-9d2ed43a-b1f8-11e7-934f-0c50d372cda8.png)

Would be great to name spaces:
Level_Number i.e. 00_100, 00_101...., 01_100, 01_101 Etc. I always Start with 100 as sorting is perfect in excel. I am referring here to spaces in the main building.

**Comment by theo-armour** [comment]
@mdengusiak 

> Shell geometry
I have been trying to avoid adding this in first generation of Build Well. There's a lot more code involved.

It will happen, but it's a matter of when. And this depends on @bwelle. If shell geometry is required for Open Studio calcs etc, then it will be added.

If not, then there will be more time to work on gbXML viewer. ;-)

> Would be possible that we isolate spaces and see them in 3D?

See also HUD menu

See wish list for mnu-settings-spaces.html

http://rawgit.com/ladybug-tools/spider/master/#build-well/README.md

> Would be great to name spaces:

@bwelle also has thoughts here

Can do. 

BTW, Space page still at very early stage. Likely to change a lot. No significant need for testing here - yet.

**Comment by bwelle** [comment]
@theo-armour @mdengusiak 

I am in the process of manually creating a gbXML file for all the objects we require for Build Well so that they not only show up correctly in OS, but they also run correctly (2 different things unfortunately). I will determine if space shell geometry is critical path or not. Working with Chien Si on this. Then will provide not only the file, but an object by object description of minimum requirements. Note: What SO requires to run may not match exactly what FZK viewer wants to see for proper import. But at least we will know EXACTLY where that boundary lies.

**Comment by bwelle** [comment]
Gents,

I did what I should have done a while ago to nail down minimum critical path objects and formatting for gbXML to Open Studio API conversions. First, I used Grasshopper to create a simple box building, 2 floors, perimeter core zoning, one single window on each floor south and west, overhangs on the windows and a rectangular fin on each windows, as well as a simple box for an adjacent building. These elements comprise of everything we need to support for our tool. See images [here](https://perkinswill.box.com/s/1e3k7vo3n8x69euxy84wde7h61ii8j8s) and [here](https://perkinswill.box.com/s/kmlexkd9o9i5r4zvez6ptbyzfbcbg0hu).

I used the OS component in Grasshopper to create on OSM file directly. I imported it into OS desktop, and confirmed the simulation ran correctly. Then I EXPORTED a gbXML file to know exactly what OS would need if I imported it. I then took that file, and started deleting some content that the OS studio app created (like loads, constructions, etc.) Then I imported it back into OS desktop to confirm it stilI worked smoothly and the simulation run (and it did). Therefore, I now have created a gbXML file that works specifically for Open Studio [here](https://perkinswill.box.com/s/z8hjp2iy3q8cgi5rhf90ucyqstygvyso). This is what we should target to mimic for the Build Well export as we are certain now it's simulation error free. It imports perfectly into the gbXML viewer v5 and it also imports correctly into FZK viewer without error.

I took a look at this file next to what is currently exported by Build Well, and below summarizing the where changes are needed.

For Space definitions, we see this in the working file:

     <Space zoneIdRef="Zone1" id="Zone1_space" buildingStoreyIdRef="Building_Story_1">
        <Name>Zone1_space</Name>
        <Area>21.000000</Area>
        <Volume>105.000000</Volume>
      </Space>

In the Build Well export we have this:

              <Space zoneIdRef="bw-zone-1" id="bw-space-6" buildingStoreyIdRef="bw-story-2" 
               conditionType="HeatedAndCooled" >
				<Name>space 6</Name>
				<Description>length front</Description>
				<Area>623.5281374238571</Area>
				<Volume>7482.337649086285</Volume>
			</Space>

The structure is the same, but in the Build Well export above at some point the zone IDs start to diverge from the space IDs. The Zone ID and the Space ID should always be the same.

For shading surfaces, the working file has this:

<Surface id="shdSurface_2_0" surfaceType="Shade">
      <RectangularGeometry>
        <Azimuth>0</Azimuth>
        <CartesianPoint>
          <Coordinate>-10.000000</Coordinate>
          <Coordinate>10.000000</Coordinate>
          <Coordinate>0.000000</Coordinate>
        </CartesianPoint>
        <Tilt>90</Tilt>
        <Width>10.000000</Width>
        <Height>10.000000</Height>
      </RectangularGeometry>
      <PlanarGeometry>
        <PolyLoop>
          <CartesianPoint>
            <Coordinate>-10.000000</Coordinate>
            <Coordinate>10.000000</Coordinate>
            <Coordinate>10.000000</Coordinate>
          </CartesianPoint>
          <CartesianPoint>
            <Coordinate>-10.000000</Coordinate>
            <Coordinate>10.000000</Coordinate>
            <Coordinate>0.000000</Coordinate>
          </CartesianPoint>
          <CartesianPoint>
            <Coordinate>-20.000000</Coordinate>
            <Coordinate>10.000000</Coordinate>
            <Coordinate>0.000000</Coordinate>
          </CartesianPoint>
          <CartesianPoint>
            <Coordinate>-20.000000</Coordinate>
            <Coordinate>10.000000</Coordinate>
            <Coordinate>10.000000</Coordinate>
          </CartesianPoint>
        </PolyLoop>
      </PlanarGeometry>
    </Surface>

In the current Build Well export we have this:

<Surface surfaceType="Shade" id="bw-shade-1" >
			<Name>building Anton</Name>
			<PlanarGeometry>
				<PolyLoop>
						<CartesianPoint>
							<Coordinate>77.07107</Coordinate>
							<Coordinate>-41.71573</Coordinate>
							<Coordinate>0</Coordinate>
						</CartesianPoint>
						<CartesianPoint>
							<Coordinate>77.07107</Coordinate>
							<Coordinate>-41.71573</Coordinate>
							<Coordinate>70</Coordinate>
						</CartesianPoint>
						<CartesianPoint>
							<Coordinate>98.28427</Coordinate>
							<Coordinate>-62.92893</Coordinate>
							<Coordinate>70</Coordinate>
						</CartesianPoint>
						<CartesianPoint>
							<Coordinate>98.28427</Coordinate>
							<Coordinate>-62.92893</Coordinate>
							<Coordinate>0</Coordinate>
						</CartesianPoint>
				</PolyLoop>
			</PlanarGeometry>
		</Surface>

So the only difference here is that we need to add the Rectangular Geometry portion of the surface definition. 

For exterior walls with windows, the working file has this:

    <Surface id="Zone6_Srf_4" surfaceType="ExteriorWall">
      <AdjacentSpaceId spaceIdRef="Zone6_space"/>
      <RectangularGeometry>
        <Azimuth>180</Azimuth>
        <CartesianPoint>
          <Coordinate>0.000000</Coordinate>
          <Coordinate>0.000000</Coordinate>
          <Coordinate>5.000000</Coordinate>
        </CartesianPoint>
        <Tilt>90</Tilt>
        <Width>10.000000</Width>
        <Height>5.000000</Height>
      </RectangularGeometry>
      <PlanarGeometry>
        <PolyLoop>
          <CartesianPoint>
            <Coordinate>0.000000</Coordinate>
            <Coordinate>0.000000</Coordinate>
            <Coordinate>10.000000</Coordinate>
          </CartesianPoint>
          <CartesianPoint>
            <Coordinate>0.000000</Coordinate>
            <Coordinate>0.000000</Coordinate>
            <Coordinate>5.000000</Coordinate>
          </CartesianPoint>
          <CartesianPoint>
            <Coordinate>10.000000</Coordinate>
            <Coordinate>0.000000</Coordinate>
            <Coordinate>5.000000</Coordinate>
          </CartesianPoint>
          <CartesianPoint>
            <Coordinate>10.000000</Coordinate>
            <Coordinate>0.000000</Coordinate>
            <Coordinate>10.000000</Coordinate>
          </CartesianPoint>
        </PolyLoop>
      </PlanarGeometry>
      <Opening openingType="FixedWindow" id="Zone6_Srf_4_glz_0">
        <RectangularGeometry>
          <Azimuth>180</Azimuth>
          <CartesianPoint>
            <Coordinate>1.464466</Coordinate>
            <Coordinate>0.000000</Coordinate>
            <Coordinate>5.732233</Coordinate>
          </CartesianPoint>
          <Tilt>90</Tilt>
          <Width>7.071068</Width>
          <Height>3.535534</Height>
        </RectangularGeometry>
        <PlanarGeometry>
          <PolyLoop>
            <CartesianPoint>
              <Coordinate>1.464466</Coordinate>
              <Coordinate>0.000000</Coordinate>
              <Coordinate>9.267767</Coordinate>
            </CartesianPoint>
            <CartesianPoint>
              <Coordinate>1.464466</Coordinate>
              <Coordinate>0.000000</Coordinate>
              <Coordinate>5.732233</Coordinate>
            </CartesianPoint>
            <CartesianPoint>
              <Coordinate>8.535534</Coordinate>
              <Coordinate>0.000000</Coordinate>
              <Coordinate>5.732233</Coordinate>
            </CartesianPoint>
            <CartesianPoint>
              <Coordinate>8.535534</Coordinate>
              <Coordinate>0.000000</Coordinate>
              <Coordinate>9.267767</Coordinate>
            </CartesianPoint>
          </PolyLoop>
        </PlanarGeometry>
      </Opening>
    </Surface>

The current Build Well export has this:

<Surface surfaceType="ExteriorWall" id="bw-surface-5" >
			<Name>ExteriorWall</Name>
			<CADOjectId>none</CADOjectId>
			<AdjacentSpaceId spaceIdRef="bw-space-3" />
			<PlanarGeometry>
				<PolyLoop>
						<CartesianPoint>
							<Coordinate>0</Coordinate>
							<Coordinate>0</Coordinate>
							<Coordinate>0</Coordinate>
						</CartesianPoint>
						<CartesianPoint>
							<Coordinate>48.98980</Coordinate>
							<Coordinate>0</Coordinate>
							<Coordinate>0</Coordinate>
						</CartesianPoint>
						<CartesianPoint>
							<Coordinate>48.98980</Coordinate>
							<Coordinate>0</Coordinate>
							<Coordinate>12</Coordinate>
						</CartesianPoint>
						<CartesianPoint>
							<Coordinate>0</Coordinate>
							<Coordinate>0</Coordinate>
							<Coordinate>12</Coordinate>
						</CartesianPoint>
				</PolyLoop>
			</PlanarGeometry>
			<Opening openingType="OperableWindow" id="bw-opening-5" >
				<PlanarGeometry>
					<PolyLoop>
						<CartesianPoint>
							<Coordinate>34.29286</Coordinate>
							<Coordinate>0</Coordinate>
							<Coordinate>8.40000</Coordinate>
						</CartesianPoint>
						<CartesianPoint>
							<Coordinate>14.69694</Coordinate>
							<Coordinate>0</Coordinate>
							<Coordinate>8.40000</Coordinate>
						</CartesianPoint>
						<CartesianPoint>
							<Coordinate>14.69694</Coordinate>
							<Coordinate>0</Coordinate>
							<Coordinate>3.60000</Coordinate>
						</CartesianPoint>
						<CartesianPoint>
							<Coordinate>34.29286</Coordinate>
							<Coordinate>0</Coordinate>
							<Coordinate>3.60000</Coordinate>
						</CartesianPoint>
					</PolyLoop>
				</PlanarGeometry>
			</Opening>
		</Surface>

Again,the only difference I see here is that we need the Rectangular Geometry addition.

For interior walls, the working file has:

<Surface id="Zone10_Srf_5" surfaceType="InteriorWall">
      <AdjacentSpaceId spaceIdRef="Zone10_space"/>
      <AdjacentSpaceId spaceIdRef="Zone6_space"/>
      <RectangularGeometry>
        <Azimuth>180</Azimuth>
        <CartesianPoint>
          <Coordinate>3.000000</Coordinate>
          <Coordinate>3.000000</Coordinate>
          <Coordinate>5.000000</Coordinate>
        </CartesianPoint>
        <Tilt>90</Tilt>
        <Width>4.000000</Width>
        <Height>5.000000</Height>
      </RectangularGeometry>
      <PlanarGeometry>
        <PolyLoop>
          <CartesianPoint>
            <Coordinate>3.000000</Coordinate>
            <Coordinate>3.000000</Coordinate>
            <Coordinate>10.000000</Coordinate>
          </CartesianPoint>
          <CartesianPoint>
            <Coordinate>3.000000</Coordinate>
            <Coordinate>3.000000</Coordinate>
            <Coordinate>5.000000</Coordinate>
          </CartesianPoint>
          <CartesianPoint>
            <Coordinate>7.000000</Coordinate>
            <Coordinate>3.000000</Coordinate>
            <Coordinate>5.000000</Coordinate>
          </CartesianPoint>
          <CartesianPoint>
            <Coordinate>7.000000</Coordinate>
            <Coordinate>3.000000</Coordinate>
            <Coordinate>10.000000</Coordinate>
          </CartesianPoint>
        </PolyLoop>
      </PlanarGeometry>
    </Surface>

The current Build Well export has this:

<Surface surfaceType="InteriorWall" id="bw-surface-6" >
			<Name>InteriorWall</Name>
			<CADOjectId>none</CADOjectId>
			<AdjacentSpaceId spaceIdRef="bw-space-3" />
			<AdjacentSpaceId spaceIdRef="bw-space-7" />
			<PlanarGeometry>
				<PolyLoop>
						<CartesianPoint>
							<Coordinate>33.98980</Coordinate>
							<Coordinate>-15</Coordinate>
							<Coordinate>0</Coordinate>
						</CartesianPoint>
						<CartesianPoint>
							<Coordinate>33.98980</Coordinate>
							<Coordinate>-15</Coordinate>
							<Coordinate>12</Coordinate>
						</CartesianPoint>
						<CartesianPoint>
							<Coordinate>-15</Coordinate>
							<Coordinate>-15</Coordinate>
							<Coordinate>12</Coordinate>
						</CartesianPoint>
						<CartesianPoint>
							<Coordinate>-15</Coordinate>
							<Coordinate>-15</Coordinate>
							<Coordinate>0</Coordinate>
						</CartesianPoint>
					</PolyLoop>
			</PlanarGeometry>
		</Surface>

Again, only difference is Rectangular Geometry.

For interior floors/ceilings, the working file has this...

<Surface id="Zone3_Srf_1" surfaceType="Ceiling">
      <AdjacentSpaceId spaceIdRef="Zone3_space"/>
      <AdjacentSpaceId spaceIdRef="Zone8_space"/>
      <RectangularGeometry>
        <Azimuth>90</Azimuth>
        <CartesianPoint>
          <Coordinate>10.000000</Coordinate>
          <Coordinate>10.000000</Coordinate>
          <Coordinate>5.000000</Coordinate>
        </CartesianPoint>
        <Tilt>0</Tilt>
        <Width>8.366600</Width>
        <Height>2.509980</Height>
      </RectangularGeometry>
      <PlanarGeometry>
        <PolyLoop>
          <CartesianPoint>
            <Coordinate>0.000000</Coordinate>
            <Coordinate>10.000000</Coordinate>
            <Coordinate>5.000000</Coordinate>
          </CartesianPoint>
          <CartesianPoint>
            <Coordinate>3.000000</Coordinate>
            <Coordinate>7.000000</Coordinate>
            <Coordinate>5.000000</Coordinate>
          </CartesianPoint>
          <CartesianPoint>
            <Coordinate>7.000000</Coordinate>
            <Coordinate>7.000000</Coordinate>
            <Coordinate>5.000000</Coordinate>
          </CartesianPoint>
          <CartesianPoint>
            <Coordinate>10.000000</Coordinate>
            <Coordinate>10.000000</Coordinate>
            <Coordinate>5.000000</Coordinate>
          </CartesianPoint>
        </PolyLoop>
      </PlanarGeometry>
    </Surface>

The current Build Well export looks like this...

<Surface surfaceType="InteriorFloor" id="bw-surface-18" >
			<Name>InteriorFloor</Name>
			<CADOjectId>none</CADOjectId>
			<AdjacentSpaceId spaceIdRef="bw-space-10" />
			<PlanarGeometry>
				<PolyLoop>
						<CartesianPoint>
							<Coordinate>28.28427</Coordinate>
							<Coordinate>-35.35534</Coordinate>
							<Coordinate>12</Coordinate>
						</CartesianPoint>
						<CartesianPoint>
							<Coordinate>28.28427</Coordinate>
							<Coordinate>35.35534</Coordinate>
							<Coordinate>12</Coordinate>
						</CartesianPoint>
						<CartesianPoint>
							<Coordinate>-28.28427</Coordinate>
							<Coordinate>35.35534</Coordinate>
							<Coordinate>12</Coordinate>
						</CartesianPoint>
						<CartesianPoint>
							<Coordinate>-28.28427</Coordinate>
							<Coordinate>-35.35534</Coordinate>
							<Coordinate>12</Coordinate>
						</CartesianPoint>
					</PolyLoop>
			</PlanarGeometry>
		</Surface>

There are quite a few differences here. First, it appears that OS wants floors/ceilings (which are the same surface) to not have the surfaceType=InteriorFloor. It will ALWAYS be surfaceType= Ceiling. Then, it will reference 2 AdjacentSpaceID spaceIDRefs, for the zones above and below it. In this case, the lower zone was listed first, and the upper zone listed second. Not sure if the reverse would cause problems but let's just keep this convention. The current Build Well export doesn't have multiple AdjacentSpaceIDs since all the roof, floor, and baseslab surfaces need to be split first (I mentioned this in prior post). In addition to splitting the surfaces, once again the Rectangular Geometry definition needs to be added.

That's it, other than adding Rectangular geometry to Roof.

As far as naming conventions for surfaces, Build Well needs the zones IDs to be named Zone-1, Zone-2, etc. with the corresponding space IDs to be Space-1, Space-2, etc.  The current naming convention for storys is fine. You'll probably want to drop the "bw-" at the beginning of each surface/space to keep it general for others.

Hopefully this was helpful!

Cheers,
Benjamain

**Comment by theo-armour** [comment]
@bwelle 

Are you sure, sure, SURE that rectangular geometry is required to complete your desired calculations?

If so, let's add a week to any related deadlines in order complete additional code and any related deadlines.

If we can do without rectangular geometry, then there's much more time to get shapes going nicely, for example.

**Comment by mdengusiak** [comment]
EXCELLENT I tested Benjamin files and works perfectly:
![2017-10-16 07_05_30](https://user-images.githubusercontent.com/14005893/31597679-a5ca1390-b241-11e7-9ac4-b3667fa4c223.gif)

I tested with two options Zone import
![image](https://user-images.githubusercontent.com/14005893/31597727-e154bb5e-b241-11e7-8683-af6f46962ded.png)

Space Import
![image](https://user-images.githubusercontent.com/14005893/31597748-ff4fb820-b241-11e7-8ecd-02cc73b7483e.png)

This is the reason I prefer to have my naming convenition :)

**Comment by bwelle** [comment]
@mdengusiak 
So if I understand correctly, you're saying Zone1 for zone, and Zone1_space for space? That's totally fine with me, as long as the zone and the space refer to the same thing using the same integer. I thought you were proposing something quite different for some reason.

@theo-armour 
I will check again re Rectangular Geometry. 10-4 if indeed required, expect a week more.

**Comment by mdengusiak** [comment]
@theo-armour 
@bwelle 

I really belive that rectangular geometry would bring lots of benefit for all users. Here are my comments:

1. this is naming explanation that I would like to see
`Level_Space+Number`:
![2017-10-16 18_41_32](https://user-images.githubusercontent.com/14005893/31627322-c92bff84-b2a4-11e7-83ac-b27110686495.png)
because
![image](https://user-images.githubusercontent.com/14005893/31627508-71051402-b2a5-11e7-9295-2e9a889d8e74.png)
see attached partially corrected your file:
[SampleBuildWellgbXMLworking4OpenStudioA.zip](https://github.com/ladybug-tools/spider/files/1388559/SampleBuildWellgbXMLworking4OpenStudioA.zip)
I am happy to use same naming for zones and spaces
![image](https://user-images.githubusercontent.com/14005893/31627771-5549ed86-b2a6-11e7-901c-4278180e94a0.png)

2. I love surface naming strategy where we reference Space-Srf... Brilliant!
![image](https://user-images.githubusercontent.com/14005893/31627653-e5b85c1e-b2a5-11e7-88c6-4b09e43d9b3f.png)

All we need t do implement better space naming and our gbXML is excellent :)
please let me know if you need some more clarification

**Comment by theo-armour** [comment]
@mdengusiak 

> I really believe that rectangular geometry would bring lots of benefit for all users. 

I agree. The issue is that @bwelle has an important presentation to give in November. So we need to figure what needs to be done before the presentation and what can wait until after the presentation.

**Comment by mdengusiak** [comment]
@theo-armour 
Sure, understood.
