### ISSUE TITLE
R12 - Statistic Numbers

### ISSUE THREAD

**Issue by mdengusiak** [ladybug-tools/spider#91]
@theo-armour 
Here is first draft for our list. I mentioned SI units but this will be gbMXL units so SI or IP:

Building height, m 
No. Of storeys (above and below ground), -
If external shading fins are present on each elevation (true /false) ? 
Passivhaus form factor = surface area / floor area ratio
Total Building Floor Area, A = m2
Total Building Volume, V = m3
A/V ration = -
External Surface  = area m2
External Opening = area m2
External Wall = area m2
UndegroundWall = area, m2
SlabonGrade = area, m2
Roof Area = m2
RoofLightArea = m2
....etc
 
We will snap to closest 8 orientation: N, E, S, W, NE, SE, NW, SW 
For each orientation:
External Surface  = area m2
External Opening = area m2
%Glazing per each orientation = %

**Comment by theo-armour** [comment]
@mdengusiak 

> Building height, m

From ground level up? The issue is that ground level is not a gbXML element or attribute so there is no easy way of calculating the building height. The total height of a building - from it lowest point to its highest point probably can be calulated.

> No. Of storeys (above and below ground), -

Number of storeys is easy. Figuring out what stories are above and below ground is not so easy - same issue as previous.

> If external shading fins are present on each elevation (true /false) ?

Do we have any models where we know there are fins or overhangs? We need some way to identify that a fin is a special type of shade surface type.

> Passivhaus form factor = surface area / floor area ratio

What surface type should be included in each type of area?

> Total Building Volume, V = m3

This may be a tricky one to calculate. Will probably start by trying to calculate the volume of all the spaces.

> External Surface = area m2

wall and roof or just wall?

**Comment by mdengusiak** [comment]
Hi I added reply to post above

**Comment by mdengusiak** [comment]
@theo-armour 
can we add to external areas: 
ExposedFloor
SlabOnGrade
UndergroundSlab
UndergroundWall


![image](https://user-images.githubusercontent.com/14005893/37908112-05d94918-30ff-11e8-927f-bc530a3e71a0.png)

**Comment by theo-armour** [comment]
@mdengusiak 

More exterior surfaces in [gbXML Viewer 12.11](http://www.ladybug.tools/spider/gbxml-viewer/dev)

**Comment by mdengusiak** [comment]
@theo-armour 
most stuff is implemented in R12.14,
we need to find a way for Volume calculations from polyloops

also we need to add notes: "All Numbers values are calculated by our engine and not relying on gbXML values"

**Comment by theo-armour** [comment]
@mdengusiak 

> we need to find a way for Volume calculations from polyloops

Added wish list item
* 2018-04-02 ~ MD/Theo ~ Add volume calculations

> we need to find a way for Volume calculations from polyloops

See r12.15
