### ISSUE TITLE
add a label for space name 

### ISSUE THREAD

**Issue by arif-hanif** [ladybug-tools/spider#98]
helpful feature to know the space, have a space name label like the tessellate pts feature.

**Comment by theo-armour** [comment]
@arif-hanif 

This is all a really interesting topic. Thanks for the input.

What are the add ways to add labels and signage within interactive 3D environments? 

Some labels could be permanent some could be _ad hoc_. Maybe labels are added automatically to a space if the space is over ten square meters etc. It's going to be a lot of fun.

In any case I see a feature like this, fingers crossed, in the R13/R14 time frame. I look forward to your feedback when it starts appearing,

See also Michal's wish list item:

https://github.com/ladybug-tools/spider/edit/master/pages/gbxml-viewer-support-issues-wish-list.md#L133

**Comment by arif-hanif** [comment]
i think based on size and zoom level, what is the best way to contribute?

do you have a road map outlining features you are currently working on and could use help on.

**Comment by theo-armour** [comment]
> what is the best way to contribute?

That's a really nice question to receive.  

Can we discuss this? So first thoughts

**Shine some light on the Solar Calculator**
Do you ever play with Solar calculotors?

The one used here I built in 2016 and is described here:

http://www.ladybug.tools/ladybug-web/tt6-ladybug-web-r1-all-in-one.html#solar-calculator-ladybug-web/readme.md

It would be so much fun to turn this primitive start into a world-class effort.

* Totally footnoted and auditable and trustworthy
* Compatible with the Ladybug Tools Python Solar calculator
* Working in Node and/or with the poplar libraries

Here's the interesting part: I think the bulk of the work should be done by non-astronomers because if it us be be widely used the code and the text should be readable by ordinary humans.

**Bridging the Python and JavaScript Worlds**
Currently there is no dialog or data sharing between Spider and the other Ladybug Tools? Why not?

Why can't we use Python for the calculations and JavaScript for the 3D display. We need to start a dialog between the two groups.

**EPW Files Online**
The whole thing of having to download files to your hard drive before you can use the data is antiquated.  

We must get the data to GitHub and make it streamable.

***

Regarding current road map, nothing long term yet. There's just too many big changes going on too see distant future clearly.

In the next few weeks:

* Get a Solar radiation analysis/tool kit going
* Continue efforts to identify issues that cause errors when going from Revit/whatever to TAS/e+/IES/whatever and learn how to save the fixes
* Continue working on the workflow so the process is intuitive and takes the fewest clicks

***

That's about it for now. I would be happy to hear about the things you wan to play with or things that could be fixed. And the best is having good wish list items

Thank you again, for the good question,

Theo

**Comment by arif-hanif** [comment]
Really good ideas @theo-armour .

I have not played around as much with solar calculator but have a ton of experience with gbxml/e+/openstudio/revit and mechanical design.

My expertise are js ( currently use Node/React ) python ( Django for web framework but can utilize node as well )

I have a couple ideas regarding EPW Files and bridging the Python/JS World.

any thoughts in standardizing around gITF
https://www.khronos.org/gltf/

using python to do the processing and just stream over web socket to Js?

**Comment by theo-armour** [comment]
> * 2018-09-05 ~ @arif-hanif / @mdengusiak  ~ Add space name labels

Added to wish list here: https://www.ladybug.tools/spider/#gbxml-viewer/r14/gv-set-settings/README.md
